// lib/demoData.ts

export const demoStudents = [
  {
    id: "1",
    name: "Aarav Sharma",
    nickname: "The Coder King",
    photo: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face",
    bio: "Full-stack developer by passion, chai enthusiast by necessity. Spent 2 years debugging code and 2 years debugging life.",
    futureDream: "CTO of a unicorn startup by 30",
    favoriteMemory: "That all-nighter before the DBMS project submission when we all survived on Maggi and hope.",
    farewellMessage: "This batch gave me more than a degree — it gave me a second family. SGSITS forever! 🎓",
    instagram: "aarav_codes",
    linkedin: "aaravsharma",
    rollNumber: "MCA/22/001",
  },
  {
    id: "2",
    name: "Priya Verma",
    nickname: "The Algorithm Queen",
    photo: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop&crop=face",
    bio: "Machine learning enthusiast who can explain neural networks but still gets lost on the SGSITS campus.",
    futureDream: "AI researcher at Google DeepMind",
    favoriteMemory: "Winning the state-level hackathon representing SGSITS Indore — the proudest moment!",
    farewellMessage: "Every lecture, every exam, every laugh in the canteen — I'll treasure it all. Batch 2026 zindabad!",
    instagram: "priya.verma.ml",
    linkedin: "priyavermaai",
    rollNumber: "MCA/22/002",
  },
  {
    id: "3",
    name: "Rohit Patel",
    nickname: "Back Bench Legend",
    photo: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop&crop=face",
    bio: "Proof that you can sit at the back and still top the class. Blockchain developer and chai-break commander.",
    futureDream: "Build India's first decentralized education platform",
    favoriteMemory: "The legendary college trip to Pachmarhi. We lost Vishal for 2 hours and found him eating poha.",
    farewellMessage: "SGSITS — where I came as a boy and left as an engineer. Nothing beats Indore's poha and this college!",
    instagram: "rohit.dev",
    linkedin: "rohitpateldev",
    rollNumber: "MCA/22/003",
  },
  {
    id: "4",
    name: "Sneha Joshi",
    nickname: "The Presentation Pro",
    photo: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop&crop=face",
    bio: "UI/UX designer who made every project presentation look like an Apple keynote. Figma is my second home.",
    futureDream: "Design lead at a Fortune 500 tech company",
    favoriteMemory: "The farewell decoration night — we stayed till 3 AM and created magic together.",
    farewellMessage: "To my batchmates: you were my inspiration, my competition, and my constants. Love you all! ✨",
    instagram: "sneha.designs",
    linkedin: "snehajoshiux",
    rollNumber: "MCA/22/004",
  },
  {
    id: "5",
    name: "Arjun Singh",
    nickname: "The DevOps Guy",
    photo: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face",
    bio: "I automate things so I can be lazy efficiently. Kubernetes wizard and Sunday cricket captain.",
    futureDream: "Lead DevOps Engineer at a global tech giant",
    favoriteMemory: "When our college server went down on exam day and we all got a holiday. Best day ever!",
    farewellMessage: "Batch 2026 — we started as strangers, became warriors. SGSITS made us who we are!",
    instagram: "arjun.devops",
    linkedin: "arjunsinghops",
    rollNumber: "MCA/22/005",
  },
  {
    id: "6",
    name: "Kavya Mehta",
    nickname: "The Data Wizard",
    photo: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400&h=400&fit=crop&crop=face",
    bio: "Data scientist who turns numbers into stories. Found love in Python, statistics, and SGSITS canteen samosas.",
    futureDream: "Head of Data Science at a leading fintech company",
    favoriteMemory: "Our batch WhatsApp group — the memes, the panic, the love. Pure gold.",
    farewellMessage: "SGSITS gave me knowledge, Indore gave me flavors, Batch 2026 gave me memories for a lifetime.",
    instagram: "kavya.data",
    linkedin: "kavyamehtads",
    rollNumber: "MCA/22/006",
  },
];

export const demoMemories = [
  {
    id: "m1",
    userId: "1",
    userName: "Aarav Sharma",
    userPhoto: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face",
    caption: "First day of MCA at SGSITS Indore — nervous, excited, and completely lost on campus. Little did I know these people standing next to me would become my forever family. 🎓❤️ #MCA2026 #SGSITS #FirstDay",
    mediaUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop",
    mediaType: "image" as const,
    likes: ["2", "3", "4", "5"],
    comments: [
      { id: "c1", userId: "2", userName: "Priya Verma", userPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=50&h=50&fit=crop", text: "I still remember that day! You were so confused 😂", createdAt: new Date("2024-01-15") }
    ],
    tags: ["firstday", "sgsits", "mca2026"],
    pinned: true,
    approved: true,
    createdAt: new Date("2022-07-15"),
  },
  {
    id: "m2",
    userId: "3",
    userName: "Rohit Patel",
    userPhoto: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop&crop=face",
    caption: "Pachmarhi trip 2023 — the trip that made us a batch and not just classmates. Every single memory from this trip is pure gold. Missing this already 🏔️🌿 #Pachmarhi #MCATripDiaries #SGSITS2026",
    mediaUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
    mediaType: "image" as const,
    likes: ["1", "2", "4", "5", "6"],
    comments: [
      { id: "c2", userId: "6", userName: "Kavya Mehta", userPhoto: "https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=50&h=50&fit=crop", text: "Best trip of our lives! 😭❤️", createdAt: new Date("2023-11-20") }
    ],
    tags: ["trip", "pachmarhi", "batch"],
    pinned: false,
    approved: true,
    createdAt: new Date("2023-11-18"),
  },
  {
    id: "m3",
    userId: "4",
    userName: "Sneha Joshi",
    userPhoto: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face",
    caption: "The farewell night setup we spent all night decorating 🌟✨ Every light, every flower, every star — placed with so much love for our beloved seniors. Now it's our turn to say goodbye... 💔 #Farewell #SGSITS #MCA2026",
    mediaUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800&h=600&fit=crop",
    mediaType: "image" as const,
    likes: ["1", "2", "3"],
    comments: [],
    tags: ["farewell", "decoration", "memories"],
    pinned: false,
    approved: true,
    createdAt: new Date("2026-04-10"),
  },
  {
    id: "m4",
    userId: "2",
    userName: "Priya Verma",
    userPhoto: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&h=100&fit=crop&crop=face",
    caption: "Hackathon win 🏆 — Representing SGSITS Indore at state level and making our professors proud! 48 hours of zero sleep, infinite chai, and unstoppable team spirit. We coded, we conquered! 💻🔥 #SGSITS #Hackathon #MCA2026 #Proud",
    mediaUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=600&fit=crop",
    mediaType: "image" as const,
    likes: ["1", "3", "5", "6"],
    comments: [
      { id: "c3", userId: "5", userName: "Arjun Singh", userPhoto: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=50&h=50&fit=crop", text: "So proud of you all! SGSITS rocks! 🚀", createdAt: new Date("2025-03-05") }
    ],
    tags: ["hackathon", "win", "proud", "sgsits"],
    pinned: true,
    approved: true,
    createdAt: new Date("2025-03-03"),
  },
];

export const demoConfessions = [
  {
    id: "conf1",
    anonymousName: "Anonymous Star ⭐",
    content: "I had a massive crush on someone in this batch for 3 full years and never said a word. Today I finally admit it. You know who you are. This is my goodbye and my confession at the same time. 💛",
    likes: 87,
    approved: true,
    createdAt: new Date("2026-04-01"),
  },
  {
    id: "conf2",
    anonymousName: "Midnight Ghost 🌙",
    content: "I submitted someone else's code in 2nd sem thinking I'd get caught. I never did. The professor even gave me a 9/10. I've been living in guilt since then. Sorry professor. I know you'll never read this but... sorry. 😅",
    likes: 142,
    approved: true,
    createdAt: new Date("2026-04-02"),
  },
  {
    id: "conf3",
    anonymousName: "Canteen Regular 🍵",
    content: "I used to sit in the canteen for 3 extra hours after class just to avoid going home because college felt more like home. These walls know my tears, my laughter, and my late-night chai orders. I'll miss it all. 😭",
    likes: 203,
    approved: true,
    createdAt: new Date("2026-04-03"),
  },
  {
    id: "conf4",
    anonymousName: "Backbench Hero 🎭",
    content: "Our entire backbench crew would share answers during internals using hand signals we invented in 1st sem. We had a whole system. The professors thought we were taking notes. We were legends. 😂",
    likes: 318,
    approved: true,
    createdAt: new Date("2026-04-04"),
  },
];

export const demoGuestbook = [
  {
    id: "g1",
    authorName: "Prof. R.K. Sharma",
    role: "teacher" as const,
    message: "It has been my absolute privilege to teach MCA Batch 2026 at SGSITS Indore. Your curiosity, dedication, and spirit are unmatched. Go out and make our institution proud. The world is waiting for your brilliance. Always remember — learning never stops. My blessings are always with you. 🙏",
    photoUrl: "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop&crop=face",
    createdAt: new Date("2026-04-08"),
  },
  {
    id: "g2",
    authorName: "Dr. Meera Jain",
    role: "teacher" as const,
    message: "Four years of growth, challenges, and triumphs. MCA Batch 2026 — you have made SGSITS proud at every step. As you step into the professional world, carry with you the values this institution has instilled. Be kind, be curious, be unstoppable. Wishing you all a bright and fulfilling future! 💫",
    photoUrl: "https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=200&h=200&fit=crop&crop=face",
    createdAt: new Date("2026-04-09"),
  },
];

export const demoTimeline = [
  {
    id: "t1",
    title: "First Day at SGSITS",
    description: "July 2022 — We walked into the gates of SGSITS Indore with nervous hearts, confused minds, and big dreams. Nobody knew then that these strangers would become a family.",
    date: "July 2022",
    imageUrl: "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=600&h=400&fit=crop",
    emoji: "🎓",
  },
  {
    id: "t2",
    title: "Fresher's Party",
    description: "September 2022 — Our seniors welcomed us with the most memorable fresher's night. The dancing, the performances, the laughter — this was the night we truly became MCA Batch 2026.",
    date: "September 2022",
    imageUrl: "https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=600&h=400&fit=crop",
    emoji: "🎉",
  },
  {
    id: "t3",
    title: "First Internal Exams",
    description: "November 2022 — The panic, the last-minute studying, the WhatsApp groups at 3 AM. We survived our first internals and discovered that Maggi at midnight is a valid study strategy.",
    date: "November 2022",
    imageUrl: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600&h=400&fit=crop",
    emoji: "📚",
  },
  {
    id: "t4",
    title: "Pachmarhi Trip",
    description: "November 2023 — The trip that turned batchmates into brothers and sisters. Mountains, waterfalls, bonfires, and memories that will last a lifetime. This trip made us US.",
    date: "November 2023",
    imageUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop",
    emoji: "🏔️",
  },
  {
    id: "t5",
    title: "Hackathon Victory",
    description: "March 2025 — Team SGSITS MCA won the state-level hackathon. 48 sleepless hours, endless chai, and a trophy that proved we were truly the best. SGSITS Indore rang across the state!",
    date: "March 2025",
    imageUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&h=400&fit=crop",
    emoji: "🏆",
  },
  {
    id: "t6",
    title: "Final Semester",
    description: "January 2026 — The last semester. Every class, every submission, every canteen break felt more precious than ever. We were all trying to hold on to these moments a little longer.",
    date: "January 2026",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=600&h=400&fit=crop",
    emoji: "⏰",
  },
  {
    id: "t7",
    title: "Farewell — The Last Chapter",
    description: "April 2026 — The night that changed everything. Tears, laughter, hugs, and promises. Dressed in our finest, saying the hardest goodbyes. MCA Batch 2026 signs off in gold.",
    date: "April 2026",
    imageUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=600&h=400&fit=crop",
    emoji: "💛",
  },
];
